<?php

/**
 * @file
 * Contains simple_affiliate.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function simple_affiliate_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'user') {
    $fields['simple_affiliate_referral'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Referrer ID'))
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'hidden',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('form', TRUE);
    return $fields;
  }
}

/**
 * Implements hook_user_insert().
 *
 */
function simple_affiliate_user_insert($entity) {
  if (isset($_COOKIE["simple_affiliate"])) {
    // Checking if the tracking cookie is present and setting the value in the
    // field.
    $referral_id = $_COOKIE["simple_affiliate"];
    $entity->set('simple_affiliate_referral', $referral_id);
    $entity->save();
  }
}
